### ISSUE TITLE
改进-严重-接口参数保存时出错未提示具体原因

### ISSUE THREAD

**Issue by NightRunner** [cehome-com/api-manager#5]
接口-编辑-保存:

出错时只会弹层报错:保存失败,      但没有提示具体的原因,在console中可以看到,最好能在弹层时加入具体的错误提示.

**Comment by maruixiang** [comment]
开发人员使用的系统，可以报具体错误。同时考虑界面友好和实用性，更好的做法是加个错误堆栈隐含层，通过点击显示错误信息

**Comment by issunlei** [comment]
@maruixiang @NightRunner 已优化
